export const filters = [
  {
    filterName: "Price",
    filterID: 3,
    Entity_Id: 1,
    filterOptions: [
      {
        filterID: 1,
        optionId: 1,
        optionTitle: "Grass",
        Entity_Id: 1,
        input_type: "range",
        range_from: "1000",
        range_to: "2500",
        Val_From: "",
        Val_To: "",
      },
    ],
  },
  {
    filterName: "Type",
    filterID: 1,
    Entity_Id: 1,
    filterOptions: [
      {
        filterID: 1,
        optionId: 1,
        optionTitle: "Grass",
        Entity_Id: 1,
        input_type: "checkbox",
        range_from: "",
        range_to: "",
        Val_From: "",
        Val_To: "",
      },
      {
        filterID: 1,
        optionId: 2,
        optionTitle: "Malathion",
        Entity_Id: 1,
        input_type: "checkbox",
        range_from: "",
        range_to: "",
        Val_From: "",
        Val_To: "",
      },
      {
        filterID: 1,
        optionId: 2,
        optionTitle: "Organic",
        Entity_Id: 1,
        input_type: "checkbox",
        range_from: "",
        range_to: "",
        Val_From: "",
        Val_To: "",
      },
    ],
  },
  {
    filterName: "Brand",
    filterID: 2,
    Entity_Id: 3,
    filterOptions: [
      {
        filterID: 2,
        optionId: 1,
        optionTitle: "ACI Formulation Ltd",
        Entity_Id: 1,
        input_type: "checkbox",
        range_from: "",
        range_to: "",
        Val_From: "",
        Val_To: "",
      },
      {
        filterID: 2,
        optionId: 2,
        optionTitle: "AgraniTraders",
        Entity_Id: 1,
        input_type: "checkbox",
        range_from: "",
        range_to: "",
        Val_From: "",
        Val_To: "",
      },
      {
        filterID: 2,
        optionId: 2,
        optionTitle: "Agrodev United",
        Entity_Id: 1,
        input_type: "checkbox",
        range_from: "",
        range_to: "",
        Val_From: "",
        Val_To: "",
      },
    ],
  },
];
